version: "3.9"

services:
  backend:
    build: ./backend
    container_name: nest-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "postgresql://neondb_owner:npg_0MH1jCLucyrf@ep-delicate-darkness-abfwdy4i-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require"
    command: npm run start:dev

  frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "4201:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run start
