CREATE TYPE "Role" AS ENUM (
  'ADMIN',
  'CLIENT'
);

CREATE TYPE "ReservationStatus" AS ENUM (
  'PENDING',
  'CONFIRMED',
  'CANCELLED',
  'COMPLETED'
);

CREATE TYPE "OrderStatus" AS ENUM (
  'PENDING',
  'DELIVERED',
  'CANCELLED'
);

CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE,
  "password" varchar,
  "firstname" varchar,
  "lastname" varchar,
  "role" "Role",
  "phone" varchar,
  "createdAt" datetime,
  "updatedAt" datetime
);

CREATE TABLE "Prestation" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "description" text,
  "duration" int,
  "price" float,
  "createdAt" datetime,
  "updatedAt" datetime,
  "categoryId" int
);

CREATE TABLE "Product" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text,
  "price" float,
  "stock" int,
  "createdAt" datetime,
  "updatedAt" datetime,
  "categoryId" int
);

CREATE TABLE "Category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text
);

CREATE TABLE "Reservation" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "startDate" datetime,
  "endDate" datetime,
  "status" "ReservationStatus",
  "price" float,
  "createdAt" datetime,
  "userId" int,
  "prestationId" int
);

CREATE TABLE "Order" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "createdAt" datetime,
  "status" "OrderStatus",
  "totalPrice" float,
  "userId" int
);

CREATE TABLE "OrderItem" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "quantity" int,
  "price" float,
  "createdAt" datetime,
  "orderId" int,
  "productId" int
);

CREATE TABLE "Review" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text,
  "rating" int,
  "visible" boolean,
  "createdAt" datetime,
  "userId" int
);

CREATE TABLE "RecurringSlot" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dayOfWeek" int,
  "startTime" varchar,
  "endTime" varchar
);

CREATE TABLE "RecurringSlotException" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" datetime
);

CREATE TABLE "OneTimeSlot" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" datetime,
  "startTime" varchar,
  "endTime" varchar
);

ALTER TABLE "Reservation" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "Reservation" ADD FOREIGN KEY ("prestationId") REFERENCES "Prestation" ("id");

ALTER TABLE "Prestation" ADD FOREIGN KEY ("categoryId") REFERENCES "Category" ("id");

ALTER TABLE "Product" ADD FOREIGN KEY ("categoryId") REFERENCES "Category" ("id");

ALTER TABLE "Order" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "OrderItem" ADD FOREIGN KEY ("orderId") REFERENCES "Order" ("id");

ALTER TABLE "OrderItem" ADD FOREIGN KEY ("productId") REFERENCES "Product" ("id");

ALTER TABLE "Review" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");
